# Generated by Django 4.1.2 on 2022-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album_id',
            field=models.IntegerField(verbose_name='Album ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
