# Generated by Django 4.1.2 on 2022-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_photo_album_id_alter_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(max_length=256, null=True, verbose_name='Link to photo'),
        ),
    ]
