# Generated by Django 4.0.3 on 2022-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('author', models.CharField(max_length=64, verbose_name='Author')),
                ('date_of_publication', models.DateField(verbose_name='Date of publication')),
                ('isbn_number', models.IntegerField(max_length=13, verbose_name='ISBN number')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages')),
                ('link_to_the_cover', models.SlugField(verbose_name='Link to the cover')),
                ('language', models.CharField(max_length=256, verbose_name='Language of publication')),
            ],
        ),
    ]
