# Generated by Django 4.0.3 on 2022-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.CharField(max_length=64, verbose_name='Date of publication'),
        ),
    ]
