# Generated by Django 4.0.1 on 2022-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='Adres dostawy'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa pizzy'),
        ),
    ]
