# Generated by Django 4.0.1 on 2022-01-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0002_cart_address_alter_pizza_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
