# Generated by Django 4.0.1 on 2022-01-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0003_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
    ]
