# Generated by Django 4.0.1 on 2022-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0004_remove_cart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
    ]
