# Generated by Django 4.0.1 on 2022-01-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0007_cart_date_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='name_topping',
        ),
    ]
