# Generated by Django 4.0.1 on 2022-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0008_rename_name_topping_name_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.IntegerField(choices=[(60, '60cm'), (50, '50cm'), (40, '40cm'), (30, '30cm')], null=True, verbose_name='Rozmiar pizzy'),
        ),
    ]
