# Generated by Django 4.0.1 on 2022-01-21 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0009_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=64, verbose_name='Adres dostawy'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.IntegerField(choices=[(60, '60cm'), (50, '50cm'), (40, '40cm'), (30, '30cm')], verbose_name='Rozmiar pizzy'),
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizza_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_elk.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=128)),
                ('apartment_address', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField()),
                ('additional_information', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza_elk.billingaddress'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(to='pizza_elk.OrderPizza'),
        ),
    ]
