# Generated by Django 4.0.1 on 2022-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0010_remove_cart_date_remove_cart_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
    ]
