# Generated by Django 4.0.1 on 2022-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0012_remove_orderpizza_quantity_pizza_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
