# Generated by Django 4.0.1 on 2022-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0013_remove_pizza_quantity_orderpizza_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='additional_information',
            field=models.TextField(),
        ),
    ]
