# Generated by Django 4.0.1 on 2022-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_elk', '0015_alter_billingaddress_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
